const data = {
  products: [
    {
      _id: '1',
      name: 'Lenovo IDEAPAD L340 RYZEN',
      category: 'Laptop',
      image: '/images/p1.png',
      price: 12000000,
      brand: 'Lenovo',
      reting: 4.5,
      numReviews: 10,
      description: 'Gaming HD laptop',
    },
    {
      _id: '2',
      name: 'Acer IDEAPAD L340 RYZEN',
      category: 'Laptop',
      image: '/images/p2.jpeg',
      price: 12000000,
      brand: 'Acer',
      reting: 3,
      numReviews: 10,
      description: 'Gaming HD laptop',
    },
    {
      _id: '3',
      name: 'Asus IDEAPAD L340 RYZEN',
      category: 'Laptop',
      image: '/images/p3.jpeg',
      price: 12000000,
      brand: 'Asus',
      reting: 4,
      numReviews: 10,
      description: 'Gaming HD laptop',
    },
    {
      _id: '4',
      name: 'HP IDEAPAD L340 RYZEN',
      category: 'Laptop',
      image: '/images/p4.jpeg',
      price: 12000000,
      brand: 'HP',
      reting: 2,
      numReviews: 10,
      description: 'Gaming HD laptop',
    },
    {
      _id: '5',
      name: 'DELL IDEAPAD L340 RYZEN',
      category: 'Laptop',
      image: '/images/p5.jpeg',
      price: 12000000,
      brand: 'DELL',
      reting: 5,
      numReviews: 10,
      description: 'Gaming HD laptop',
    },
  ],
};
export default data;