const data = {
  products: [
    {
      _id: "1",
      name: "Lenovo IDEAPAD L340 RYZEN",
      category: "Laptop",
      image: "/images/p1.png",
      price: 3000000,
      countInStck: 1,
      brand: "Lenovo",
      rating: 1.5,
      numReviews: 2,
      description: "Gaming HD laptop",
    },
    {
      _id: "2",
      name: "Acer IDEAPAD L340 RYZEN",
      category: "Laptop",
      image: "/images/p2.jpeg",
      price: 5000000,
      countInStck: 10,
      brand: "Acer",
      rating: 4,
      numReviews: 12,
      description: "Gaming HD laptop",
    },
    {
      _id: "3",
      name: "Asus IDEAPAD L340 RYZEN",
      category: "Laptop",
      image: "/images/p3.jpeg",
      price: 22000000,
      countInStck: 0,
      brand: "Asus",
      rating: 4.5,
      numReviews: 30,
      description: "Gaming HD laptop",
    },
    {
      _id: "4",
      name: "HP IDEAPAD L340 RYZEN",
      category: "Laptop",
      image: "/images/p4.jpeg",
      price: 7000000,
      countInStck: 4,
      brand: "HP",
      rating: 2,
      numReviews: 4,
      description: "Gaming HD laptop",
    },
    {
      _id: "5",
      name: "DELL IDEAPAD L340 RYZEN",
      category: "Laptop",
      image: "/images/p5.jpeg",
      price: 14000000,
      countInStck: 20,
      brand: "DELL",
      rating: 0,
      numReviews: 4,
      description: "Gaming HD laptop",
    },
  ],
};
export default data;
